# Generated by Django 5.2.8 on 2025-11-13 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("쿠폰", "쿠폰"), ("입장권", "입장권"), ("응모권", "응모권")],
                        max_length=20,
                    ),
                ),
                ("required_stamps", models.IntegerField()),
                ("expiry_days", models.IntegerField(default=90)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "보상",
                "verbose_name_plural": "보상들",
                "db_table": "rewards",
                "ordering": ["required_stamps"],
            },
        ),
        migrations.CreateModel(
            name="ClaimedReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("사용 가능", "사용 가능"), ("만료됨", "만료됨"), ("사용됨", "사용됨")],
                        default="사용 가능",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claimed_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="chat.reward",
                    ),
                ),
            ],
            options={
                "verbose_name": "받은 보상",
                "verbose_name_plural": "받은 보상들",
                "db_table": "claimed_rewards",
                "ordering": ["-claimed_date"],
            },
        ),
        migrations.CreateModel(
            name="Stamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(db_index=True, max_length=100)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stamps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "스탬프",
                "verbose_name_plural": "스탬프들",
                "db_table": "stamps",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_images/%Y/%m/%d/")),
                ("place_name", models.CharField(blank=True, max_length=100, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 이미지",
                "verbose_name_plural": "사용자 이미지들",
                "db_table": "user_images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
